
---
- name: Update apt cache (if needed)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Ensure Nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: present
  become: yes
  notify: Restart Nginx

- name: Deploy index.html page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart Nginx

- name: Ensure Nginx is started and enabled on boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: yes