version: '3.8'


services:
  api:
    build:
      context: ./app/api
      dockerfile: Dockerfile
      target: development


    command: [ "air", "-c", ".air.toml" ]




    container_name: hit-counter-api
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - GIN_MODE=debug
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=testuser
      - DB_PASSWORD=testpassword
      - DB_NAME=hitcounter_db

    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - ./app/api:/app
    restart: unless-stopped
    networks:
      - hitcounter_network

  postgres_db:
    image: postgres:17-alpine
    container_name: hit-counter-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=hitcounter_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d hitcounter_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    networks:
      - hitcounter_network



networks:
  hitcounter_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
