
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "APP_PORT=${APP_PORT:-8080} GIN_MODE=${GIN_MODE:-debug} DB_HOST=${DB_HOST} DB_PORT=${DB_PORT} DB_USER=${DB_USER} DB_PASSWORD=${DB_PASSWORD} DB_NAME=${DB_NAME} ./tmp/main" # Command to run the binary
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
log = "air_errors.log"
delay = 1000 # ms
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true