{{- if .Values.api.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" .Values.api.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.api.name }}
    helm.sh/chart: {{ include "hit-counter-system.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: application
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # If you need path rewriting because your app expects requests at root,
    # but your ingress path is, for example, /api/v1:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # This would typically be used with a path like: /api/v1(/|$)(.*)
    # For now, let's assume your Go app handles the /api/v1 prefix.
spec:
  {{- if .Values.api.ingress.ingressClassName }}
  ingressClassName: {{ .Values.api.ingress.ingressClassName }}
  {{- end }}
  rules:
    - host: {{ .Values.api.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path }}
            pathType: {{ .Values.api.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ printf "%s-service" .Values.api.name }}
                port:
                  name: {{ .Values.api.ingress.servicePortName | default "http" }}
  {{- if .Values.api.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.api.ingress.host | quote }}
      secretName: {{ .Values.api.ingress.tls.secretName }}
  {{- end }}
{{- end }}