{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pvc" .Values.postgresql.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
    helm.sh/chart: {{ include "hit-counter-system.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce # Standard for databases
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
  {{- if (ne "-" .Values.postgresql.persistence.storageClass) }}
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}