{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" .Values.postgresql.name }}
  namespace: {{  .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
    helm.sh/chart: {{ include "hit-counter-system.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: database
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}