apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: hit-counter-app
data:
  APP_PORT: "8080"
  GIN_MODE: "release"
  DB_HOST: "postgres-db-service"
  DB_PORT: "5432"
  DB_NAME: "hitcounter_k8s_db"