apiVersion: apps/v1
kind: Deployment
metadata:
  name: hit-counter-api
  namespace: hit-counter-app
  labels:
    app: hit-counter-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: hit-counter-api

  template:
    metadata:
      labels:
        app: hit-counter-api
    spec:
      containers:
        - name: hit-counter-api
          image: hit-counter-api:k8s-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
