apiVersion: v1
kind: Service
metadata:
  name: hit-counter-api-service
  namespace: hit-counter-app

spec:
  selector:
    app: hit-counter-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: NodePort