name: Go CI Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'app/api/**.go'
      - 'app/api/go.mod'
      - 'app/api/go.sum'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/api/**.go'
      - 'app/api/go.mod'
      - 'app/api/go.sum'

jobs:
  build:
    name: Build and Test Go API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/api

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v -o hit-counter-api .
